name: Coveralls Single Test Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  single-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wait on all tests to finish
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          running-workflow-name: Coveralls report
          allowed-conclusions: success,skipped,cancelled,failure

      - name: Download artifact
        id: artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ github.event.pull_request.number}}
          workflow: coveralls.yml
          workflow_conclusion: success

      - uses: coverallsapp/github-action@v2.3.0
        with:
          format: lcov
          debug: true
