name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_number:
          - 1
          - 2

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test ${{ matrix.test_number }}
        run: make test-coveralls-${{ matrix.test_number }}

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          flag-name: run-${{  join(matrix.*, '-') }}
  finish:
    needs: coverage
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: 'run-1,run-2'
